version: 0.2

phases:
  install:
    runtime-versions:
      nodeJs: 19
    commands:
      - yarn install -g typescript
      - yarn install
  build:
    commands:
      - yarn build
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
  name: away-9ja-$(date +%Y-%m-%d)
