version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g yarn typescript
      - yarn install
  build:
    commands:
      - yarn build
      - yarn generate

artifacts:
  files:
    - yarn.lock
    - package.json
    - 'build/**/*'
    - 'node_modules/**/*'
    - '.platform/**/*' # AWS Elastic Beanstalk configuration files
    - '.ebextensions/**/*' # AWS Elastic Beanstalk configuration files
  name: deploy-nodejs-build-artifacts
  discard-paths: no
